<?php

use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Drupal\event_subscriber\Event\CustomEvent;
use Drupal\event_subscriber\Event\CustomEventNode;
use Drupal\Core\Entity\EntityInterface;



function event_subscriber_node_insert(EntityInterface $node) {
    // $database = \Drupal::database();
    // kint($node->language()->getId());
    // $database->insert('node')->fields(array('nid' => $node->id(),
    //   'type' => $node->bundle(),'uuid' => $node->uuid(),
    //   'langcode' => $node->language()->getId()))
    // ->execute();
  $event = new CustomEventNode($node);
  $dispatcher = \Drupal::service('event_dispatcher');
  $dispatcher->dispatch(CustomEvent::NODE_INSERT, $event);
}


